### ISSUE TITLE
Throws on few nested object hierarchy

### ISSUE THREAD

**Issue by aph5nt** [purkayasta/Dumpper#2]
For few nested objects it thows on dump()

System.InvalidOperationException : Could not find color or style 'xxx.Data.DbModels.Sender'.
   at Spectre.Console.StyleParser.Parse(String text) in /_/src/Spectre.Console/StyleParser.cs:line 13
   at Spectre.Console.MarkupParser.Parse(String text, Style style) in /_/src/Spectre.Console/Internal/Text/Markup/MarkupParser.cs:line 26
   at Dumpper.Writer.Printer.GenerateTree[T](T instance, PropertyInfo[] properties, String className)
   at Dumpper.Writer.Printer.Print[T](PropertyInfo[] properties, String className, T instance)
   at Dumpper.GenericExtensions.Dump[T](T instance)

**Comment by purkayasta** [comment]
Hello @aph5nt, can you give me a little bit more context with pseudo code?

**Comment by purkayasta** [comment]
@aph5nt fixed it in the latest version. can you verify with the latest version?
